apiVersion: apps/v1
kind: Deployment
metadata:
  name: mobile
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mobile
  template:
    metadata:
      labels:
        app: mobile
    spec:
      containers:
      - name: mobile
        image: mobile:latest
        ports:
        - containerPort: 4000
        envFrom:
        - configMapRef:
            name: mobile-config
        - secretRef:
            name: mobile-secrets