apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev # Altere para "prod" no ambiente de produção
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer # Expõe o frontend externamente
